### ISSUE TITLE
No valid configuration file? And what's this about "key_listener?"

### ISSUE THREAD

**Issue by Owen5819** [savbell/whisper-writer#62]
I installed WhisperWriter, apparently successfully, and filled out the settings window that came up automatically. Config.yaml and config.schema.yaml both contain information I input. But when I tried to start WhisperWriter, this appeared:

(venv) C:\WhisperWriter2>python run.py
Starting WhisperWriter...
No valid configuration file found. Opening settings window...
Traceback (most recent call last):
  File "C:\WhisperWriter2\src\main.py", line 106, in restart_app
    self.cleanup()
  File "C:\WhisperWriter2\src\main.py", line 92, in cleanup
    if self.key_listener:
       ^^^^^^^^^^^^^^^^^
AttributeError: 'WhisperWriterApp' object has no attribute 'key_listener'
FWIW, c:\WhisperWriter\ contains "key_listener.py".

How do I open the settings window if WhisperWriter won't come up? And what do I do then? Or does it really need something else entirely?

Thanks.

**Comment by Owen5819** [comment]
Sorry to be a helpless newbie, but there it is.

**Comment by Enyium** [comment]
When initially running it, I received the following output:

```
Starting WhisperWriter...
WARNING: CPU random generator seem to be failing, disabling hardware random number generation
WARNING: RDRND generated: 0xffffffff 0xffffffff 0xffffffff 0xffffffff
Warning: QT_DEVICE_PIXEL_RATIO is deprecated. Instead use:
   QT_AUTO_SCREEN_SCALE_FACTOR to enable platform plugin controlled per-screen factors.
   QT_SCREEN_SCALE_FACTORS to set per-screen DPI.
   QT_SCALE_FACTOR to set the application global scale factor.
No valid configuration file found. Opening settings window...
Traceback (most recent call last):
  File "C:\redacted\whisper-writer\src\main.py", line 106, in restart_app
    self.cleanup()
  File "C:\redacted\whisper-writer\src\main.py", line 92, in cleanup
    if self.key_listener:
       ^^^^^^^^^^^^^^^^^
AttributeError: 'WhisperWriterApp' object has no attribute 'key_listener'
```

After running it again and configuring my settings with the GUI, which I could only do then, I didn't get this error anymore.

So, this seems to be an error that every new user first gets, and should be solved for a better user experience and less deterrence. "No valid configuration file found. Opening settings window..." is just informational output, but maybe code thereafter unconditionally assumes the configuration is already available.
